spring:
  application:
    name: transporte-clientes
  datasource:
    url: jdbc:mysql://localhost:3306/msrv_clientes
    username: micro_clientes
    password: transporte_c_msrv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

server:
  port: 0

transporte:
  sapi:
    gateway: http://localhost:4040
    Logs:
      saveRequest: ${transporte.sapi.gateway}/api/v1/logs/